### PR TITLE
added a script to downlaod the index from website automatically 

### PR DESCRIPTION
**Pull request by Jorigorn**
Curl and wget is not woking, since the download website requird password.
Which make cummbumsome to donwload the data in server command line.

Thanks. :）

### CODE REVIEW

**Comment by octavian-ganea** [comment]
Very nice! Thanks! Can you please remove line 21 ?  I'll then accept the pull request.

**Comment by Jorigorn** [comment]
> Very nice! Thanks! Can you please remove line 21 ? I'll then accept the pull request.

@octavian-ganea Hi, I removed the line 21. Thanks for open source the project. Very helpful. :)

**Comment by hofmannt** [comment]
Can you remove me, so that I don’t get these messages? Thanks!

Thomas


On Oct 26, 2018, at 15:37, Jorigorn Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


Very nice! Thanks! Can you please remove line 21 ? I'll then accept the pull request.

@octavian-ganea<https://github.com/octavian-ganea> Hi, I removed the line 21. Thanks for open source the project. Very helpful. :)

**Comment by hofmannt** [comment]
That is not acceptable. Just remove me or create a new group. Sorry.

Thomas

Sent from my iPhone

On 28 Oct 2018, at 12:15, Octavian Ganea <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #11<https://github.com/dalab/pboh-entity-linking/pull/11> into master.

**Pull request merged**
